# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cov_i <- function(x, y) {
    .Call(`_crowdopt_cov_i`, x, y)
}

cov_n <- function(x, y) {
    .Call(`_crowdopt_cov_n`, x, y)
}

var_i <- function(x) {
    .Call(`_crowdopt_var_i`, x)
}

var_n <- function(x) {
    .Call(`_crowdopt_var_n`, x)
}

