# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cov_i <- function(x, y) {
    .Call(`_crowdopt_cov_i`, x, y)
}

cov_n <- function(x, y) {
    .Call(`_crowdopt_cov_n`, x, y)
}

var_i <- function(x) {
    .Call(`_crowdopt_var_i`, x)
}

var_n <- function(x) {
    .Call(`_crowdopt_var_n`, x)
}

weighted_mean_ii <- function(x, w) {
    .Call(`_crowdopt_weighted_mean_ii`, x, w)
}

weighted_mean_in <- function(x, w) {
    .Call(`_crowdopt_weighted_mean_in`, x, w)
}

weighted_mean_ni <- function(x, w) {
    .Call(`_crowdopt_weighted_mean_ni`, x, w)
}

weighted_mean_nn <- function(x, w) {
    .Call(`_crowdopt_weighted_mean_nn`, x, w)
}

